### ISSUE TITLE
Лемма 1 Матлог лек 2

### ISSUE THREAD

**Issue by maxim092001** [Jovvik/M3137year2019#122]
Для полноты понимания хотелось бы доказательство...

**Comment by victor1234544** [comment]
![изображение](https://user-images.githubusercontent.com/29694517/121074794-03c6eb80-c7dd-11eb-9a85-e707db7ad985.png)
я это с пдфки 2-ой практики взял

**Comment by maxim092001** [comment]
считаю что это можно вставлять в конспект
