### ISSUE TITLE
2 сем, 1 лекция, матан

### ISSUE THREAD

**Issue by brenscrazy** [Jovvik/M3137year2019#21]
В конце 1 страницы: при х близких к х0

**Comment by Jovvik** [comment]
Можешь пояснить, где именно?

**Comment by brenscrazy** [comment]
![image](https://user-images.githubusercontent.com/32305955/74370814-cc168200-4de8-11ea-9203-423c31044a40.png)

**Comment by Jovvik** [comment]
Понял, у меня в пдфке сдвинуто было
