### ISSUE TITLE
2.12

### ISSUE THREAD

**Issue by Mee-Tree** [Jovvik/M3137year2019#24]
Судя по определению аналитической функции с вики,
> Аналити́ческая функция вещественной переменной — функция, которая совпадает со своим рядом Тейлора в окрестности любой точки области определения.

пример неаналитической находится в самом начале [3 лекции](https://github.com/Jovvik/M3137year2019/blob/master/analysis/2sem/3.pdf), прямо перед неправильным сложением.

**Comment by Jovvik** [comment]
Спасибо, сейчас поправлю
