### ISSUE TITLE
Теорема 0.1. Лекция 4.

### ISSUE THREAD

**Issue by maxim092001** [Jovvik/M3137year2019#39]
1. Пункт существование единственного Фи.

Кохась: P(a) -> Q(b) принадлежит C^r гладкое.
Конспект: P(a) -> Q(b) принадлежит C^r.

Наверное, гладкость важна.

**Comment by Jovvik** [comment]
кВ лекции 4 не было "P(a) -> Q(b)". Мб речь про последнюю теорему лекции 3?

Согласно [вики](https://ru.wikipedia.org/wiki/%D0%93%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0%D1%8F_%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F) r-гладкие функции это C^r, то есть C^r гладкое и C^r - одно и то же

**Comment by maxim092001** [comment]
Да, речь про ласт теорему 3й лекции.
Окэй, поверим вики.
