### ISSUE TITLE
Необходимое условие относительного локального экстремума

### ISSUE THREAD

**Issue by xe11us** [Jovvik/M3137year2019#50]
5.tex, строка 383
Равенство выполняется в силу (3), а не (1). И (3) не должно давать нам конец доказательства, потому что это просто сумма известных фактов, но вот что тогда доказывает теорему не могу сказать, непонятно

**Comment by Jovvik** [comment]
Да, действительно в силу (3). В условии теоремы набагано - там должен быть плюс (так на википедии)
